version: '2'
services:
  twitch:
    build: .
    volumes:
      - ./config:/config
      - videos:/videos
#      - /mattiasa/public_html/podcast:/videos
    working_dir: /videos
    environment:
      - BASEURL=http://internal.coloti.se/~mattiasa/podcast/
      - XDG_CONFIG_HOME=/config
volumes:
  videos:
    driver: local
    driver_opts:
      type: cifs
      o: vers=3.02,user=${USERNAME},pass=${PASSWORD}
      device: "//10.237.237.7/mattiasa/public_html/podcast"
